# Generated by Django 6.0.5 on 2026-06-10 12:03

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defualt.jpg', upload_to=user.models.user_directory),
        ),
    ]
